### ISSUE TITLE
Packaging comments

### ISSUE THREAD

**Issue by mcepl** [whot/HelloDevice#1]
It [builds in Koji](https://koji.fedoraproject.org/koji/taskinfo?taskID=19616950), but I have two comments:

1. What is the version? Is '1' the official version of this release or should I say the version is 0 and just go with git commit numbers?

2. Could you get ``README.md`` to the tarball as well? It is it the only documentation we have, isn’t it?

3. Also, is this supposed to run as a daemon? Should I make a systemd unit file for it?

**Comment by whot** [comment]
Version: I'll do systemd-style version, so just an incrementing number. "1" is the current version
README: see commit notification above
daemon: has to run in the background, but how you run this is mostly up to you. Best is probably using the autostart functionality from gnome because it requires the X server, not anything else. A systemd scope could work, a systemd daemon is likely to just fail with a missing DISPLAY most of the time (and there's no code to survive that).

**Comment by whot** [comment]
btw, happy to add a section to the readme on how to install it as autostart if you send me a PR for that :)

I think this one is closed now though

**Comment by mcepl** [comment]
OK, if you like ``less``-style versioning ([``less``](http://www.greenwoodsoftware.com/less/) used this style when Lennart was still in his diapers), then you should follow it. The last version should be ``2``, shouldn't it?

Concerning the autostart, let me investigate whether there is some best practice for doing it.
